### ISSUE TITLE
500 response:  Undefined method 'size' for the nil:NilClass 

### ISSUE THREAD

**Issue by bwm-epimorphics** [epimorphics/hpi-explorer#105] opened 2015-02-12 20:47 UTC
From the log file

I, [2015-02-11T15:24:30.715311 #29700]  INFO -- : Started POST "/app/hpi/preview" for 95.131.110.123 at 2015-02-11 15:24:30 +0000
I, [2015-02-11T15:24:30.716164 #29700]  INFO -- : Processing by PreviewController#create as JSON
I, [2015-02-11T15:24:30.720589 #29700]  INFO -- :   Rendered hpi/_selected_location.html.haml (3.4ms)
W, [2015-02-11T15:24:30.720735 #29700]  WARN -- : No explicit error page for exception undefined method `size' for nil:NilClass - NoMethodError
I, [2015-02-11T15:24:30.723945 #29700]  INFO -- :   Rendered public/landing/500.html (0.6ms)
I, [2015-02-11T15:24:30.728472 #29700]  INFO -- : Completed 500 Internal Server Error in 8ms (Views: 2.9ms)

**Comment by ijdickinson** [comment] 2015-02-12 23:03
Not enough information to diagnose or reproduce. What was the incoming request?

**Comment by bwm-epimorphics** [comment] 2015-02-14 11:16
This look like the matching entry from the Apache log file.
[[
10.31.37.21, 194.168.91.106, 95.131.110.123 - - [11/Feb/2015:15:24:30 +0000] "POST /app/hpi/preview HTTP/1.1" 500 4963  "http://landregistry.data.gov.uk/app/hpi/hpi?from_m=1&from_y=2014&loc_0=Bournemouth&loc_uri_0=http%3A%2F%2Flandregistry.data.gov.uk%2Fid%2Fregion%2Fbournemouth&m_chm=1&m_chy=1&m_hpi=1&m_vol=1&source=preview_form&to_m=1&to_y=2015" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
]]

In a sample of a day on one server there was only one of these.

**Comment by ijdickinson** [comment] 2015-09-22 10:56
I'm not able to reproduce this. Closing, but please re-open if we have a way to reproduce it.

**Closed by ijdickinson** 2015-09-22 10:56 UTC
